### ISSUE TITLE
Folders by Creature Type

### ISSUE THREAD

**Issue by melek** [bobifle/tokens#1]
My system lags considerably when opening the Tokens folder, because there are so many. It would be wonderful if there was a little folder organization to break up the load!

Would it be possible to parse the Creature Type and and place the tokens in appropriate folders, with the POI folder in the root 'Tokens' folder for quick access?

I am happy to edit and run the script myself so I can customize the output, but I think I'd need a little installation guidance/orientation to the repo.

**Comment by bobifle** [comment]
I agree. MT does a poor job of populating the library thumbnail, and it tends to "block", resulting in a bad user experience. Since there's a "search subdirectory" option, using subdirectories may improve things.
