### ISSUE TITLE
Creature Info as tags in Filename

### ISSUE THREAD

**Issue by melek** [bobifle/tokens#2]
Since the token names are embedded, it would be awfully neat if the filenames had a format with key information such as Size, Creature Type, and CR to filter them by in the Resource Library or (OS for drag-and-drop); for example:

Guard Medium Humanoid CR1-8.rptok (the hyphen represents the slash in 1/8 CR)
Aboleth Large Aberration CR10.rptok
Tarrasque Gargantuan Monstrosity CR30.rptok

Maybe there are better ways to tag them, but filename tagging is durable and portable. Of course, it might look ugly to some people, but it would make deep/subdirectory searches in the Resource Library very useful :)

**Comment by bobifle** [comment]
no text

**Comment by bobifle** [comment]
I'm not sure about this one. It's a war we cannot win because we can only tag very few info in the filename and I'm not a big fan of it to begin with.

There are online tools than can do such things very easily, and once you grab the monster names, you can search the tokens by name.

**Comment by melek** [comment]
Fair enough. The new subdirectories already make it much easier to look for a certain kind of monster.

I think CR would be the only 'tag' that would be important enough to consider if we have to choose 1, I'd say size would be a distant second! 

If only there were a way to 'tag' tokens to be filterable in the library... but that's a request for MT generally ;) In the meantime I'll take your suggestion of using Kobold Fight Club or similar to filter by CR, etc.
